name: GitLab Mirror

on:
  push:
    branches:
      - main

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0  # v7.0.0
        with:
          fetch-depth: 0

      - name: Push to GitLab
        run: |
          git remote add gitlab "https://\${{ secrets.GITLAB_MIRROR_USER }}:\${{ secrets.GITLAB_MIRROR_TOKEN }}@gitlab.com/orchard-cde/orchard-vscode-extension.git"
          git push gitlab HEAD:main
