name: GitLab Mirror

on:
  push:
    branches:
      - main

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
        with:
          fetch-depth: 0

      - name: Push to GitLab
        run: |
          git remote add gitlab "https://${{ secrets.GITLAB_MIRROR_USER }}:${{ secrets.GITLAB_MIRROR_TOKEN }}@gitlab.com/orchard-cde/orchard-vscode-extension.git"
          git push gitlab HEAD:main
